language: python

python:
    - 2.6
    - 2.7

sudo: false

env:
    - DJANGO=1.4.16
    - DJANGO=1.5.11
    - DJANGO=1.6.8
    - DJANGO=1.7.1

matrix:
    exclude:
        - python: 2.6
          env: DJANGO=1.7.1

before_install:
    - bash bin/check_signoff.sh
    - pip install -q flake8
    - flake8 modeltree

install:
    - pip install -q coverage Django==$DJANGO

script:
    - coverage run test_suite.py

after_success:
    - pip install -q coveralls
    - coveralls
